{
  "formatVersion": "1.1",
  "component": {
    "group": "NetspendAndroidSdk",
    "module": "netspendsdk",
    "version": "release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "6tysdrhblfdgdhhm5oit6yc564"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "de.adorsys.android",
          "module": "securestoragelibrary",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.41"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.41"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services",
          "version": {
            "requires": "11.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "netspendsdk-release-sources.jar",
          "url": "netspendsdk-release-sources.jar",
          "size": 23978,
          "sha512": "e7695cb4d9f353799994d6b46761f86f5599f06cc8deb8298fc3dd43fb3994f66b74613ab1f814e754986c19ea3058b2f928a0b5737661ee4914846884062e63",
          "sha256": "5ec46bcaad6402e607a5c7831dcec7e78f861f953831a1e705417b94917b1203",
          "sha1": "a612120f3e90e045f7bbc4cf0dacffcd9caa391b",
          "md5": "fd698e0d7570d7f6555ba02b53cde8e9"
        },
        {
          "name": "netspendsdk-release.aar",
          "url": "netspendsdk-release.aar",
          "size": 147478,
          "sha512": "ae2e2dd81adb86d636417a797f17550c426cc0dada0205cf51bab8c1dac9592c44fdd18ac19eec7bf1ef86fac464517a9d079b89a0851078a569778112ace1df",
          "sha256": "57744ee6bf46c6903f219e0a582100b095fdf56c79dfbaa87586ec8febb731c9",
          "sha1": "609b80b3f99fdab90a7d3d403c0f97c28f1a119c",
          "md5": "e241a980d3579bcff3f15dedd5e870a4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "de.adorsys.android",
          "module": "securestoragelibrary",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "netspendsdk-release-sources.jar",
          "url": "netspendsdk-release-sources.jar",
          "size": 23978,
          "sha512": "e7695cb4d9f353799994d6b46761f86f5599f06cc8deb8298fc3dd43fb3994f66b74613ab1f814e754986c19ea3058b2f928a0b5737661ee4914846884062e63",
          "sha256": "5ec46bcaad6402e607a5c7831dcec7e78f861f953831a1e705417b94917b1203",
          "sha1": "a612120f3e90e045f7bbc4cf0dacffcd9caa391b",
          "md5": "fd698e0d7570d7f6555ba02b53cde8e9"
        },
        {
          "name": "netspendsdk-release.aar",
          "url": "netspendsdk-release.aar",
          "size": 147478,
          "sha512": "ae2e2dd81adb86d636417a797f17550c426cc0dada0205cf51bab8c1dac9592c44fdd18ac19eec7bf1ef86fac464517a9d079b89a0851078a569778112ace1df",
          "sha256": "57744ee6bf46c6903f219e0a582100b095fdf56c79dfbaa87586ec8febb731c9",
          "sha1": "609b80b3f99fdab90a7d3d403c0f97c28f1a119c",
          "md5": "e241a980d3579bcff3f15dedd5e870a4"
        }
      ]
    }
  ]
}
