# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

xcversion(version: "12.4") #Select 12.4 by default

platform :ios do
  desc "Build framework"
  lane :build_framework do
    xcodebuild(
      scheme: "Netspend_TestApp",
      configuration: "debug",
      clean: true,
      build: true
    )
  end
end
