# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

xcversion(version: "12.4") #Select 12.4 by default

platform :ios do
    desc "Description of what the lane does"
    lane :build do
        ENV['MATCH_PASSWORD'] = 'netspend-dev123'
        ENV['APP_BUNDLE_VERSION'] = ENV['bamboo_buildNumber'] ? ENV['bamboo_buildNumber'] : '0000'

        # match(
        #   git_url: 'ssh://git@bitbucket.hq.netspend.com:7999/int/mobile-certificates.git',
        #   username: 'webappteam@netspend.com',
        #   team_id: '74QFD47C26',
        #   git_branch: 'development',
        #   type: 'development',
        #   app_identifier: 'com.netspend.mobileapp.testApp',
        #   readonly: true,
        #   clone_branch_directly: true,
        #   shallow_clone: true
        # )
        gym(
        export_method: 'development',
        scheme: "Netspend_TestApp",
        project:'Netspend_TestApp.xcodeproj',
        configuration: 'Debug',
        clean: true,
        # skip_archive: true,
        # skip_build_archive: true,
        # skip_codesigning: true,
        # destination: 'platform=iOS Simulator,name=iPhone 11',
        output_directory: '../../apps',
        # skip_package_ipa: 'true',
        output_name: 'testApp')
        # gym(export_method: 'development', workspace: 'Netspend.xcworkspace', scheme: 'Netspend', configuration: 'Debug')

    end
end
